// src/routes/components/projects.svelte
<style lang="scss">
    .projects {
        height: 100%;
        margin-left: 3%;
        .row {
            display: flex;
            gap: 5%;
            .project {
                width: 45%;
                img {
                    width: 100%;
                    height: 70%;
                }
            }
        }
    }
</style>

<div class="projects" id="projects">
    <div class="row">
        <div class="project">
            <img src="project-imgs/rogger-img.png" alt="rogger project preview">
            <h3><a href="https://github.com/Hukasx0/rogger" target="_blank">Rogger</a></h3>
            <p>Very lightweight, easy to use, secure, Rust-based Blogging Content Management System. Created with simplicity of use in mind (all operations on the blog are performed through the GUI in the admin panel), cms forces us to watch over security by generating secure, truly random passwords (no more passwords like password123), speed is obtained using the Rust language, optimization and saving Last 100 posts in ram for faster loading. The lightness of the software is due to the Rust language, the Sqlite library and the Redis database.</p>
            <p>Tech stack: Rust, Actix, SQLite, Redis, PicoCss, HTML, JavaScript, Docker, Shell/Bash</p>
        </div>
        <div class="project">
            <img src="project-imgs/zsp2-wagrowiec-img.png" alt="zsp2wagrowiec website project preview">
            <h3><a href="https://hukasx0.github.io/zsp2wagrowiec-strona/" target="_blank">ZSP2 Wagrowiec website</a></h3>
            <p>A dynamic, responsive website without a backend using the Rest API of the school website. The website took first place in the competition for a school website.</p>
            <p>Tech stack: HTML, CSS, Bootstrap, JavaScript, JQuery</p>
        </div>
    </div>
</div>

// src/components/Projects.tsx
import type { Component } from "solid-js";
import roggerImage from "../assets/rogger-img.png";
import zsp2Image from "../assets/zsp2-wagrowiec-img.png";

const Projects: Component = () => {
    return (
        <div>
        <div class="card lg:card-side bg-base-100 shadow-xl">
  <figure><img src={roggerImage} alt=""/></figure>
  <div class="card-body w-1/2">
    <h2 class="card-title">Rogger</h2>
    <div class="flex flex-row">
        <div class="badge badge-neutral">Rust</div>
        <div class="badge badge-primary">Actix</div>
        <div class="badge badge-secondary">SQLite</div>
        <div class="badge badge-accent">JavaScript</div>
        <div class="badge badge-ghost">Docker</div>
    </div>
    <p>Very lightweight, efficient, secure and easy to use Blog Content Management System</p>
    <div class="card-actions justify-end">
      <a href="https://github.com/Hukasx0/rogger" target="_blank"><button class="btn btn-primary">GitHub</button></a>
    </div>
  </div>
</div>
    <div class="card lg:card-side bg-base-100 shadow-xl">
    <figure><img src={zsp2Image} alt=""/></figure>
    <div class="card-body w-1/2">
      <h2 class="card-title">ZSP2 Wagrowiec website</h2>
      <div class="flex flex-row">
        <div class="badge badge-neutral">HTML</div>
        <div class="badge badge-primary">Bootstrap</div>
        <div class="badge badge-secondary">CSS</div>
        <div class="badge badge-accent">JavaScript</div>
        <div class="badge badge-ghost">JQuery</div>
    </div>
      <p>The website that won the school contest, the website automatically fetches the latest data from the school backend</p>
      <div class="card-actions justify-end">
        <a href="https://hukasx0.github.io/zsp2wagrowiec-strona/" target="_blank"><button class="btn btn-primary">Website</button></a>
        <a href="https://github.com/Hukasx0/zsp2wagrowiec-strona" target="_blank"><button class="btn btn-primary">GitHub</button></a>
      </div>
    </div>
  </div>
  </div>
    );
}

export default Projects;
